/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ProcessedIngredient {
    name: string;
    isHarmful: boolean;
}
export interface FoodAnalysisResult {
    status: HealthStatus;
    sugarLevel: Level;
    calories: bigint;
    healthScore: bigint;
    fatLevel: Level;
    foodName: string;
}
export interface IngredientScanResult {
    processedIngredients: Array<ProcessedIngredient>;
    harmfulCount: bigint;
}
export interface UserProfile {
    age: bigint;
    weight: bigint;
    healthConditions: Array<HealthCondition>;
}
export enum HealthCondition {
    highCholesterol = "highCholesterol",
    none = "none",
    highBloodPressure = "highBloodPressure",
    obesity = "obesity",
    heartDisease = "heartDisease",
    diabetes = "diabetes"
}
export enum HealthStatus {
    safe = "safe",
    harmful = "harmful",
    moderate = "moderate"
}
export enum Level {
    Low = "Low",
    High = "High",
    Medium = "Medium"
}
export interface backendInterface {
    analyzeFood(foodName: string): Promise<FoodAnalysisResult | null>;
    getAllFoods(): Promise<Array<FoodAnalysisResult>>;
    getFoodStats(foodName: string): Promise<{
        sugarLevel: Level;
        calories: bigint;
        healthScore: bigint;
        fatLevel: Level;
    } | null>;
    getHealthWarnings(foodName: string): Promise<{
        status: string;
        warnings: Array<string>;
    }>;
    getUserHealthConditions(): Promise<Array<HealthCondition>>;
    getUserHealthStats(): Promise<{
        age: bigint;
        weight: bigint;
    } | null>;
    getUserProfile(): Promise<UserProfile | null>;
    saveUserProfile(profile: UserProfile): Promise<void>;
    scanIngredients(ingredients: Array<string>): Promise<IngredientScanResult>;
}
import type { FoodAnalysisResult as _FoodAnalysisResult, HealthCondition as _HealthCondition, HealthStatus as _HealthStatus, Level as _Level, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async analyzeFood(arg0: string): Promise<FoodAnalysisResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeFood(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeFood(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFoods(): Promise<Array<FoodAnalysisResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFoods();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFoods();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFoodStats(arg0: string): Promise<{
        sugarLevel: Level;
        calories: bigint;
        healthScore: bigint;
        fatLevel: Level;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFoodStats(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFoodStats(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHealthWarnings(arg0: string): Promise<{
        status: string;
        warnings: Array<string>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getHealthWarnings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHealthWarnings(arg0);
            return result;
        }
    }
    async getUserHealthConditions(): Promise<Array<HealthCondition>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserHealthConditions();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserHealthConditions();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserHealthStats(): Promise<{
        age: bigint;
        weight: bigint;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserHealthStats();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserHealthStats();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveUserProfile(to_candid_UserProfile_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveUserProfile(to_candid_UserProfile_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async scanIngredients(arg0: Array<string>): Promise<IngredientScanResult> {
        if (this.processError) {
            try {
                const result = await this.actor.scanIngredients(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.scanIngredients(arg0);
            return result;
        }
    }
}
function from_candid_FoodAnalysisResult_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FoodAnalysisResult): FoodAnalysisResult {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_HealthCondition_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HealthCondition): HealthCondition {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_HealthStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HealthStatus): HealthStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Level_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Level): Level {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FoodAnalysisResult]): FoodAnalysisResult | null {
    return value.length === 0 ? null : from_candid_FoodAnalysisResult_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        age: bigint;
        weight: bigint;
    }]): {
    age: bigint;
    weight: bigint;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        sugarLevel: _Level;
        calories: bigint;
        healthScore: bigint;
        fatLevel: _Level;
    }]): {
    sugarLevel: Level;
    calories: bigint;
    healthScore: bigint;
    fatLevel: Level;
} | null {
    return value.length === 0 ? null : from_candid_record_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sugarLevel: _Level;
    calories: bigint;
    healthScore: bigint;
    fatLevel: _Level;
}): {
    sugarLevel: Level;
    calories: bigint;
    healthScore: bigint;
    fatLevel: Level;
} {
    return {
        sugarLevel: from_candid_Level_n6(_uploadFile, _downloadFile, value.sugarLevel),
        calories: value.calories,
        healthScore: value.healthScore,
        fatLevel: from_candid_Level_n6(_uploadFile, _downloadFile, value.fatLevel)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    weight: bigint;
    healthConditions: Array<_HealthCondition>;
}): {
    age: bigint;
    weight: bigint;
    healthConditions: Array<HealthCondition>;
} {
    return {
        age: value.age,
        weight: value.weight,
        healthConditions: from_candid_vec_n11(_uploadFile, _downloadFile, value.healthConditions)
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _HealthStatus;
    sugarLevel: _Level;
    calories: bigint;
    healthScore: bigint;
    fatLevel: _Level;
    foodName: string;
}): {
    status: HealthStatus;
    sugarLevel: Level;
    calories: bigint;
    healthScore: bigint;
    fatLevel: Level;
    foodName: string;
} {
    return {
        status: from_candid_HealthStatus_n4(_uploadFile, _downloadFile, value.status),
        sugarLevel: from_candid_Level_n6(_uploadFile, _downloadFile, value.sugarLevel),
        calories: value.calories,
        healthScore: value.healthScore,
        fatLevel: from_candid_Level_n6(_uploadFile, _downloadFile, value.fatLevel),
        foodName: value.foodName
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    highCholesterol: null;
} | {
    none: null;
} | {
    highBloodPressure: null;
} | {
    obesity: null;
} | {
    heartDisease: null;
} | {
    diabetes: null;
}): HealthCondition {
    return "highCholesterol" in value ? HealthCondition.highCholesterol : "none" in value ? HealthCondition.none : "highBloodPressure" in value ? HealthCondition.highBloodPressure : "obesity" in value ? HealthCondition.obesity : "heartDisease" in value ? HealthCondition.heartDisease : "diabetes" in value ? HealthCondition.diabetes : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    safe: null;
} | {
    harmful: null;
} | {
    moderate: null;
}): HealthStatus {
    return "safe" in value ? HealthStatus.safe : "harmful" in value ? HealthStatus.harmful : "moderate" in value ? HealthStatus.moderate : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
}): Level {
    return "Low" in value ? Level.Low : "High" in value ? Level.High : "Medium" in value ? Level.Medium : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HealthCondition>): Array<HealthCondition> {
    return value.map((x)=>from_candid_HealthCondition_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FoodAnalysisResult>): Array<FoodAnalysisResult> {
    return value.map((x)=>from_candid_FoodAnalysisResult_n2(_uploadFile, _downloadFile, x));
}
function to_candid_HealthCondition_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HealthCondition): _HealthCondition {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    weight: bigint;
    healthConditions: Array<HealthCondition>;
}): {
    age: bigint;
    weight: bigint;
    healthConditions: Array<_HealthCondition>;
} {
    return {
        age: value.age,
        weight: value.weight,
        healthConditions: to_candid_vec_n20(_uploadFile, _downloadFile, value.healthConditions)
    };
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HealthCondition): {
    highCholesterol: null;
} | {
    none: null;
} | {
    highBloodPressure: null;
} | {
    obesity: null;
} | {
    heartDisease: null;
} | {
    diabetes: null;
} {
    return value == HealthCondition.highCholesterol ? {
        highCholesterol: null
    } : value == HealthCondition.none ? {
        none: null
    } : value == HealthCondition.highBloodPressure ? {
        highBloodPressure: null
    } : value == HealthCondition.obesity ? {
        obesity: null
    } : value == HealthCondition.heartDisease ? {
        heartDisease: null
    } : value == HealthCondition.diabetes ? {
        diabetes: null
    } : value;
}
function to_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<HealthCondition>): Array<_HealthCondition> {
    return value.map((x)=>to_candid_HealthCondition_n21(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
