/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const HealthStatus = IDL.Variant({
  'safe' : IDL.Null,
  'harmful' : IDL.Null,
  'moderate' : IDL.Null,
});
export const Level = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
});
export const FoodAnalysisResult = IDL.Record({
  'status' : HealthStatus,
  'sugarLevel' : Level,
  'calories' : IDL.Nat,
  'healthScore' : IDL.Nat,
  'fatLevel' : Level,
  'foodName' : IDL.Text,
});
export const HealthCondition = IDL.Variant({
  'highCholesterol' : IDL.Null,
  'none' : IDL.Null,
  'highBloodPressure' : IDL.Null,
  'obesity' : IDL.Null,
  'heartDisease' : IDL.Null,
  'diabetes' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'weight' : IDL.Nat,
  'healthConditions' : IDL.Vec(HealthCondition),
});
export const ProcessedIngredient = IDL.Record({
  'name' : IDL.Text,
  'isHarmful' : IDL.Bool,
});
export const IngredientScanResult = IDL.Record({
  'processedIngredients' : IDL.Vec(ProcessedIngredient),
  'harmfulCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'analyzeFood' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(FoodAnalysisResult)],
      ['query'],
    ),
  'getAllFoods' : IDL.Func([], [IDL.Vec(FoodAnalysisResult)], ['query']),
  'getFoodStats' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'sugarLevel' : Level,
            'calories' : IDL.Nat,
            'healthScore' : IDL.Nat,
            'fatLevel' : Level,
          })
        ),
      ],
      ['query'],
    ),
  'getHealthWarnings' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'status' : IDL.Text, 'warnings' : IDL.Vec(IDL.Text) })],
      ['query'],
    ),
  'getUserHealthConditions' : IDL.Func(
      [],
      [IDL.Vec(HealthCondition)],
      ['query'],
    ),
  'getUserHealthStats' : IDL.Func(
      [],
      [IDL.Opt(IDL.Record({ 'age' : IDL.Nat, 'weight' : IDL.Nat }))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
  'saveUserProfile' : IDL.Func([UserProfile], [], []),
  'scanIngredients' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IngredientScanResult],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const HealthStatus = IDL.Variant({
    'safe' : IDL.Null,
    'harmful' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const Level = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const FoodAnalysisResult = IDL.Record({
    'status' : HealthStatus,
    'sugarLevel' : Level,
    'calories' : IDL.Nat,
    'healthScore' : IDL.Nat,
    'fatLevel' : Level,
    'foodName' : IDL.Text,
  });
  const HealthCondition = IDL.Variant({
    'highCholesterol' : IDL.Null,
    'none' : IDL.Null,
    'highBloodPressure' : IDL.Null,
    'obesity' : IDL.Null,
    'heartDisease' : IDL.Null,
    'diabetes' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'weight' : IDL.Nat,
    'healthConditions' : IDL.Vec(HealthCondition),
  });
  const ProcessedIngredient = IDL.Record({
    'name' : IDL.Text,
    'isHarmful' : IDL.Bool,
  });
  const IngredientScanResult = IDL.Record({
    'processedIngredients' : IDL.Vec(ProcessedIngredient),
    'harmfulCount' : IDL.Nat,
  });
  
  return IDL.Service({
    'analyzeFood' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(FoodAnalysisResult)],
        ['query'],
      ),
    'getAllFoods' : IDL.Func([], [IDL.Vec(FoodAnalysisResult)], ['query']),
    'getFoodStats' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'sugarLevel' : Level,
              'calories' : IDL.Nat,
              'healthScore' : IDL.Nat,
              'fatLevel' : Level,
            })
          ),
        ],
        ['query'],
      ),
    'getHealthWarnings' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'status' : IDL.Text, 'warnings' : IDL.Vec(IDL.Text) })],
        ['query'],
      ),
    'getUserHealthConditions' : IDL.Func(
        [],
        [IDL.Vec(HealthCondition)],
        ['query'],
      ),
    'getUserHealthStats' : IDL.Func(
        [],
        [IDL.Opt(IDL.Record({ 'age' : IDL.Nat, 'weight' : IDL.Nat }))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
    'saveUserProfile' : IDL.Func([UserProfile], [], []),
    'scanIngredients' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IngredientScanResult],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };