/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FoodAnalysisResult {
  'status' : HealthStatus,
  'sugarLevel' : Level,
  'calories' : bigint,
  'healthScore' : bigint,
  'fatLevel' : Level,
  'foodName' : string,
}
export type HealthCondition = { 'highCholesterol' : null } |
  { 'none' : null } |
  { 'highBloodPressure' : null } |
  { 'obesity' : null } |
  { 'heartDisease' : null } |
  { 'diabetes' : null };
export type HealthStatus = { 'safe' : null } |
  { 'harmful' : null } |
  { 'moderate' : null };
export interface IngredientScanResult {
  'processedIngredients' : Array<ProcessedIngredient>,
  'harmfulCount' : bigint,
}
export type Level = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null };
export interface ProcessedIngredient { 'name' : string, 'isHarmful' : boolean }
export interface UserProfile {
  'age' : bigint,
  'weight' : bigint,
  'healthConditions' : Array<HealthCondition>,
}
export interface _SERVICE {
  'analyzeFood' : ActorMethod<[string], [] | [FoodAnalysisResult]>,
  'getAllFoods' : ActorMethod<[], Array<FoodAnalysisResult>>,
  'getFoodStats' : ActorMethod<
    [string],
    [] | [
      {
        'sugarLevel' : Level,
        'calories' : bigint,
        'healthScore' : bigint,
        'fatLevel' : Level,
      }
    ]
  >,
  'getHealthWarnings' : ActorMethod<
    [string],
    { 'status' : string, 'warnings' : Array<string> }
  >,
  'getUserHealthConditions' : ActorMethod<[], Array<HealthCondition>>,
  'getUserHealthStats' : ActorMethod<
    [],
    [] | [{ 'age' : bigint, 'weight' : bigint }]
  >,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'saveUserProfile' : ActorMethod<[UserProfile], undefined>,
  'scanIngredients' : ActorMethod<[Array<string>], IngredientScanResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];